version: "3.8"
services:
  bio:
    container_name: python_bio
    build: ./project
    depends_on:
      - db
    entrypoint: ["bash"]

  db:
    container_name: postgres_bio
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ribosome
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bio_data

volumes:
  postgres_data: